services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"   # HTTP‑порт
      - "9000:9000"   # TCP‑порт для драйвера
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sirius-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirius-bot
    restart: on-failure
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      # Переменные для чат‑модуля
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      LLM_PROXY_URL: "${LLM_PROXY_URL}"
      # Переменные для модуля requests_api
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DB: "default"
      LOG_LEVEL: "INFO"
      LOG_FILE: "app.log"

volumes:
  clickhouse_data:
