services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  
      - "9000:9000"   
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sirius-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirius-bot
    restart: on-failure
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      LLM_PROXY_URL: "${LLM_PROXY_URL}"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DB: "default"
      LOG_LEVEL: "INFO"
      LOG_FILE: "app.log"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
   
    depends_on:
      - sirius-bot
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

volumes:
  clickhouse_data: